//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciYonetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonemDers
    {
        public int Id { get; set; }
        public int Donem_Id { get; set; }
        public int Ders_Id { get; set; }
        public int Ogretmen_Id { get; set; }
        public System.TimeSpan BaslamaSaati { get; set; }
        public Nullable<System.TimeSpan> BitisSaati { get; set; }
        public string DersGunu { get; set; }
        public string SinifAdi { get; set; }
        public byte Kapasite { get; set; }
        public byte DersiAlanOgrenciSayisi { get; set; }
        public bool Statu { get; set; }
        public int Kullanici_Id { get; set; }
        public System.DateTime KayitTarihi { get; set; }
    
        public virtual Ders Ders { get; set; }
        public virtual Donem Donem { get; set; }
        public virtual Ogretmen Ogretmen { get; set; }
    }
}
