//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciYonetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesajlar
    {
        public int Id { get; set; }
        public string Icerik { get; set; }
        public int AliciUye_Id { get; set; }
        public bool Statu { get; set; }
        public int Kullanici_Id { get; set; }
        public System.DateTime KayitTarihi { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
    }
}
