//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolEntities : DbContext
    {
        public SchoolEntities()
            : base("name=SchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Course_Log> Course_Log { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Department_Log> Department_Log { get; set; }
        public virtual DbSet<ErrorLog> ErrorLog { get; set; }
        public virtual DbSet<Faculty> Faculty { get; set; }
        public virtual DbSet<Faculty_Log> Faculty_Log { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<Period> Period { get; set; }
        public virtual DbSet<PeriodCourse> PeriodCourse { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Student_Log> Student_Log { get; set; }
        public virtual DbSet<StudentCourse> StudentCourse { get; set; }
        public virtual DbSet<StudentCourse_Log> StudentCourse_Log { get; set; }
        public virtual DbSet<StudentGradePointAverage> StudentGradePointAverage { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<Teacher_Log> Teacher_Log { get; set; }
    }
}
