//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Period
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Period()
        {
            this.PeriodCourse = new HashSet<PeriodCourse>();
            this.StudentGradePointAverage = new HashSet<StudentGradePointAverage>();
        }
    
        public int Id { get; set; }
        public string PeriodName { get; set; }
        public int YearOfPeriod { get; set; }
        public System.DateTime SatartOfPeriod { get; set; }
        public System.DateTime EndOfPeriod { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public bool Statu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PeriodCourse> PeriodCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentGradePointAverage> StudentGradePointAverage { get; set; }
    }
}
