//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.StudentCourse = new HashSet<StudentCourse>();
            this.StudentGradePointAverage = new HashSet<StudentGradePointAverage>();
        }
    
        public int Id { get; set; }
        public int StudentNo { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public string Phone { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Adress { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public bool Statu { get; set; }
        public string TcIdentityNo { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public byte Period { get; set; }
        public byte Class { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentCourse> StudentCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentGradePointAverage> StudentGradePointAverage { get; set; }
    }
}
