//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCourse
    {
        public int Id { get; set; }
        public Nullable<int> Student_Id { get; set; }
        public Nullable<int> Course_Id { get; set; }
        public Nullable<int> Midterm_1 { get; set; }
        public Nullable<int> Midterm_2 { get; set; }
        public Nullable<int> FinalExam { get; set; }
        public string LetterNote { get; set; }
        public bool Statu { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> Period_Id { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
    }
}
