//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Log
    {
        public int Id { get; set; }
        public int StudentNo { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int Department_Id { get; set; }
        public string TcIdentityNo { get; set; }
        public string Phone { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Adress { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public bool Statu { get; set; }
        public string LogType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<byte> Period { get; set; }
        public Nullable<byte> Class { get; set; }
    }
}
