//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentGradePointAverage
    {
        public int Id { get; set; }
        public Nullable<int> Student_Id { get; set; }
        public Nullable<int> Period_Id { get; set; }
        public decimal YANO { get; set; }
        public int YanoNumberOfCredits { get; set; }
        public decimal AGNO { get; set; }
        public int AgnoNumberOfCredits { get; set; }
        public bool Statu { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual Period Period { get; set; }
        public virtual Student Student { get; set; }
    }
}
