//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciYonetimSistemi.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ders", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class Ders : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DersAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GrupNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KrediSayisiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DersAdi {
            get {
                return this.DersAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.DersAdiField, value) != true)) {
                    this.DersAdiField = value;
                    this.RaisePropertyChanged("DersAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GrupNo {
            get {
                return this.GrupNoField;
            }
            set {
                if ((this.GrupNoField.Equals(value) != true)) {
                    this.GrupNoField = value;
                    this.RaisePropertyChanged("GrupNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KrediSayisi {
            get {
                return this.KrediSayisiField;
            }
            set {
                if ((this.KrediSayisiField.Equals(value) != true)) {
                    this.KrediSayisiField = value;
                    this.RaisePropertyChanged("KrediSayisi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertLesson", ReplyAction="http://tempuri.org/IService1/InsertLessonResponse")]
        string InsertLesson(OgrenciYonetimSistemi.ServiceReference1.Ders data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertLesson", ReplyAction="http://tempuri.org/IService1/InsertLessonResponse")]
        System.Threading.Tasks.Task<string> InsertLessonAsync(OgrenciYonetimSistemi.ServiceReference1.Ders data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllLessons", ReplyAction="http://tempuri.org/IService1/GetAllLessonsResponse")]
        OgrenciYonetimSistemi.ServiceReference1.Ders[] GetAllLessons();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllLessons", ReplyAction="http://tempuri.org/IService1/GetAllLessonsResponse")]
        System.Threading.Tasks.Task<OgrenciYonetimSistemi.ServiceReference1.Ders[]> GetAllLessonsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : OgrenciYonetimSistemi.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<OgrenciYonetimSistemi.ServiceReference1.IService1>, OgrenciYonetimSistemi.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertLesson(OgrenciYonetimSistemi.ServiceReference1.Ders data) {
            return base.Channel.InsertLesson(data);
        }
        
        public System.Threading.Tasks.Task<string> InsertLessonAsync(OgrenciYonetimSistemi.ServiceReference1.Ders data) {
            return base.Channel.InsertLessonAsync(data);
        }
        
        public OgrenciYonetimSistemi.ServiceReference1.Ders[] GetAllLessons() {
            return base.Channel.GetAllLessons();
        }
        
        public System.Threading.Tasks.Task<OgrenciYonetimSistemi.ServiceReference1.Ders[]> GetAllLessonsAsync() {
            return base.Channel.GetAllLessonsAsync();
        }
    }
}
