//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciYonetimSistemi.Models.SqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hatalog
    {
        public int Error_Id { get; set; }
        public Nullable<int> HataNumara { get; set; }
        public Nullable<int> HataDurum { get; set; }
        public Nullable<int> HataSeviye { get; set; }
        public Nullable<int> HataSatir { get; set; }
        public string HataProcedure { get; set; }
        public string HataMesaj { get; set; }
        public Nullable<System.DateTime> HataTarih { get; set; }
    }
}
