//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciYonetimSistemi.Models.SqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrenciDers
    {
        public int Id { get; set; }
        public int Ogrenci_Id { get; set; }
        public int DonemDers_Id { get; set; }
        public byte Sinav_1 { get; set; }
        public byte Sinav_2 { get; set; }
        public byte Final { get; set; }
        public string HarfNotu { get; set; }
        public bool Statu { get; set; }
        public int Kullanici_Id { get; set; }
        public System.DateTime KayitTarihi { get; set; }
    
        public virtual DonemDers DonemDers { get; set; }
        public virtual Ogrenci Ogrenci { get; set; }
    }
}
